version: 2

updates:

  - package-ecosystem: "github-actions"
    directory: "/.github"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/strapi"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/vue-cli"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
