query ($id: ID!) {
  item (id: $id) {
    id
    title
    description
    categories {
      id
      title
    }
    user {
      id
      username
      email
    }
    created_at
    updated_at
    status {
      id
      title
      colour
    }
  }
}
