query {
  itemTypes {
    id
    title
    items {
      id
      title
      description
      sticky
      categories {
        id
        title
      }
      status {
        id
        title
        colour
      }
    }
  }
}
