name: strapi

on:
  push:
    paths:
    - 'strapi/**'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14.15.4

    - uses: borales/actions-yarn@v2.3.0
      with:
        cmd: --cwd strapi install

    - uses: borales/actions-yarn@v2.3.0
      with:
        cmd: --cwd strapi build
