name: strapi

on:
  push:
    paths:
    - 'strapi/**'

defaults:
  run:
    working-directory: strapi

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14.15.4

    - run: npm ci

    - run: npm run build
